# Generated by Django 4.1.7 on 2023-04-23 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_id', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ghl_contact',
            },
        ),
        migrations.RemoveField(
            model_name='loanpool',
            name='loan_id',
        ),
        migrations.CreateModel(
            name='ContactHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.PositiveSmallIntegerField()),
                ('action_name', models.CharField(max_length=255)),
                ('action_data', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='src.contact')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='src.loanpool')),
            ],
            options={
                'db_table': 'ghl_contact_history',
            },
        ),
    ]
